name: Build/release

on:
  push:
    branches:
      - '*'
      - 'feature/*'
    tags:
      - v*
  pull_request:
    branches:
      - main
      
# env:
#   DEBUG: '*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4.1.4
        with:
          submodules: recursive
      
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm ci
      
      - name: Build project
        run: npm run build

      - name: Run NodeJS Tests
        run: npm run test

      - name: Set release version
        run: python3 -c "import os; tag = os.environ['GITHUB_REF'].split('/')[-1]; f = open(os.environ['GITHUB_ENV'], 'a'); f.write('RELEASE_VERSION='+tag); f.close();"

      # - name: Upload to Github releases
      #   shell: bash
      #   run: gh release upload ${{ env.RELEASE_VERSION }} "$(find ./build -name *.tar.gz)" --clobber
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   if: startsWith(github.ref, 'refs/tags/v')

      # - name: Upload to Github releases
      #   uses: actions/upload-artifact@v3
      #   with:
      #     path: |
      #       build/**/*.tar.gz
      #   if: startsWith(github.ref, 'refs/tags/v')